line-length = 100
target-version = "py39"

[lint]
select = ["E","F","I","UP","B","SIM","C4"]
ignore = [
    "E203","E266","E501",
    "E402",
    "E701","E702",
    "E722",
    "E741",
    "UP006","UP007","UP035","UP045",
    "B008",
    "B904",
    "B007","B006","B017","B026",
    "SIM102","SIM103","SIM105","SIM108","SIM117","SIM118",
    "C401","C403","C414",
    "F841",
    "F811",
    "E712",
    "E731",
    "SIM110","SIM115","SIM210",
    "F403",
]
